### ISSUE TITLE
Forgot Axios?

### ISSUE THREAD

**Issue by EdgeCaseBerg** [NBoas42/GoodReadsSearch-FrontEnd#1]
I think you might have forgotten a commit in your package.json file? 

<img width="583" alt="Screen Shot 2022-12-14 at 2 58 43 PM" src="https://user-images.githubusercontent.com/1691564/207701687-df5aff0f-e287-4a05-8ed1-f2f84b4d3a17.png">

**Comment by NBoas42** [comment]
Hmmm might be something funky going on with how it got installed with npm. I went ahead and removed those imports since they aren't being used and I generated a new lock file without those dependencies. You should be able to just pull in master again. Let me know if that fixed it for you.

**Comment by NBoas42** [comment]
What is odd is that even after uninstalling those packages on my end and leaving the import in to try and reproduce the error my dev server was still able to build. This framework is still entirely new to me 😅

**Comment by EdgeCaseBerg** [comment]
> You should be able to just pull in master again. Let me know if that fixed it for you.

<img width="481" alt="Screen Shot 2022-12-14 at 4 07 16 PM" src="https://user-images.githubusercontent.com/1691564/207713990-1c3090e7-e3eb-4fda-bf69-56f505864ed6.png">

It did! Thanks :) 

![im-in-matrix](https://user-images.githubusercontent.com/1691564/207714075-d8cbbe98-00e5-4673-881a-640d25cb47bf.gif)

**Comment by NBoas42** [comment]
![image](https://user-images.githubusercontent.com/7351429/207715515-3e036d80-9911-4f2c-9add-5732278a52ca.png)

**Comment by NBoas42** [comment]
![giphy](https://user-images.githubusercontent.com/7351429/207716196-c1f429f1-d575-457d-9c9f-d69a495dbb5d.gif)
